spring:
  application:
    name: booting
---
spring:
  config:
    active:
      on-profile: dev
server:
  port:9090
---
  spring:
    config:
      active:
        on-profile: test
  server:
    port:9000
---
  spring:
    jpa:
      hibernate:
        dll-auto: none

---
  spring:
    h2:
      console:
        enable: true
---
 spring:
   datasource:
     url: jdbc:h2:mem:testes